name: rapido
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  supabase_flutter: ^1.0.0
  image_picker: ^0.8.6
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  icons_plus: ^4.0.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  fluttertoast: ^8.2.6

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/plats.jpeg
    - assets/images/mlawi.png
    - assets/images/berg.png
    - assets/images/frecasse.png
    - assets/images/sandwich.png
    - assets/images/12.png
    - assets/images/brik.jpg
    - assets/images/brika.jpg
    - assets/images/baguette.jpg
    - assets/images/baguettee.jpg
    - assets/images/chapati.jpg
    - assets/images/chapatii.jpg
    - assets/images/coscous.png
    - assets/images/ojja.png
    - assets/images/ojja.png
    - assets/images/makrouna.png
    - assets/images/slata.png
    - assets/images/avatar_bleu.jpg
    - assets/images/logoD17.png
    - assets/images/img_QR.png
    - assets/images/paymee.png
    - assets/images/pay.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
